name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
  env:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.VUE_APP_NAME }}