name: learn-github-actions
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show dev secrets
        env:
            VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: echo ${{ secrets.VUE_APP_NAME }}
      
      - name: Create env file
        run: |
          echo "VUE_APP_NAME=${{ secrets.VUE_APP_NAME }}" >> list.env
          echo "VUE_APP_1=${{ secrets.VUE_APP_1 }}" >> list.env
          echo "VUE_APP_2=${{ secrets.VUE_APP_2 }}" >> list.env
      
      - name: docker compose
        run: docker-compose up --build -d

      # - name: Build the Docker image
      #   run: docker build -t test .

      # - name: Run the Docker container
      #   run: docker run -d  --env-file env.list -p 8080:8080 --name test_container -d test
        

      - name: Install ngrok
        run: |
          mkdir -p $HOME/bin
          curl -s -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o $HOME/bin/ngrok.zip
          unzip -o $HOME/bin/ngrok.zip -d $HOME/bin
        env:
          NGROK_SECRET_KEY: ${{ secrets.NGROK_SECRET_KEY}} # ngrokの認証トークンをGitHubのSecretsに設定しておく必要があります

      - name: Start ngrok
        run: |
          $HOME/bin/ngrok authtoken ${{ secrets.NGROK_SECRET_KEY}}
          $HOME/bin/ngrok http --host-header=rewrite 8080