name: learn-github-actions
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show dev secrets
        env:
            VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: echo ${{ secrets.VUE_APP_NAME }}

      - name: Build the Docker image
        run: docker build -t test .

      - name: Run the Docker container
        run: docker run -d -e "VUE_APP_NAME=${VUE_APP_NAME}" -p 8080:8080 --name test_container -d test
      
      - name: Ngrok Tunnel Action
        uses: LuisBoto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 8080
          ngrok_authtoken: ${{ secrets.NGROK_SECRET_KEY}}
          tunnel_type: http
          save_url_to_filename: tunnelURL.md

      # - name: Ngrok TCP Tunelling
      #   uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      #   with:
      #     timeout: 1h
      #     port: 8080
      #     ngrok_authtoken: ${{ secrets.NGROK_SECRET_KEY}}

      # - name: Install ngrok
      #   run: |
      #     mkdir -p $HOME/bin
      #     curl -s -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o $HOME/bin/ngrok.zip
      #     unzip -o $HOME/bin/ngrok.zip -d $HOME/bin
      #   env:
      #     NGROK_SECRET_KEY: ${{ secrets.NGROK_SECRET_KEY}} # ngrokの認証トークンをGitHubのSecretsに設定しておく必要があります

      # - name: Start ngrok
      #   run: |
      #     $HOME/bin/ngrok authtoken ${{ secrets.NGROK_SECRET_KEY}}
      #     $HOME/bin/ngrok http --host-header=rewrite 8080