name: learn-github-actions
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Show dev secrets
        env:
            VUE_APP_NAME: ${{ vars.VUE_APP_NAME }}
        run: echo ${{ vars.VUE_APP_NAME }}

      - name: Build the Docker image
        run: docker build -t myapp .

      - name: Run the Docker container
        run: docker run -e "API_SECRET=${API_SECRET}" myapp