name: learn-github-actions
on: [push]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show dev secrets
        env:
            VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: echo ${{ secrets.VUE_APP_NAME }}

      - name: Build the Docker image
        run: docker build -t test .

      - name: Run the Docker container
        run: docker run -d -e "VUE_APP_NAME=${VUE_APP_NAME}" -p 8080:80 --name test_container -d test